appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: eqjgM5YCU6U7ig4zUAFvQIoAbqx4eK2bnOJJ0a5qSvACp23nim4ja0gbuOQXPNL6Hyc74qnsZ8lZSJ3x5zpsDVTWq04sncDz2jvweBJMzEi7Um3iLyZwOWqA+JgVjOP+2NfNAqksQiryAPhbYyk6JUIsa2qq6GfYDkTxUZZv3JmG3itIjn6t6HCj6czoJKlfjGXn2zFAjM00ww3ZBEFe7JN3x9zu6RJypM0JP8sMKlL5xYyMm2Ehbg65dR9Qgwm5ZIE4TzQVAahDnFq1xPMlZby857c7KeNLh8032gHoyKSmh4Dqr/jgRl6bElAfizP3pj9eHH6KSdiFjOcZKo75NZQG1xGzqigyDutKv8p+lWbRMeSMyvZZFIGQCmaZsSX3ClS1klkNkZzZEy53vQ2nnQ1WRAzmvvrc5TN0caMGJwGdxKaby16XGH53muRmuiKwKHxZjSAIGufw6PmFOIaqfM+5DdMF2GWRIctFyXu/cE8ugZZcI4Y/z08qAwapx7sCQtMZgVzQEqWoPXsqdOOlDOHwd0ymycDA4MaK+NVeC0TYxbc2KHJYPoZeIIttpIxA6B72XjzjJ06AH6Dw4zjKTsxvVWUB9/4LdTOkhuw/TbPxW9MaX90HLC4OIVO6ybz2VNNf+7EdlfaHv35IpsF65dE2bSsDJKCJUSyiSc3bPJ4=}
bot:
  automerge: true
